# Generated by Django 4.1.7 on 2023-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subjects_taught",
            field=models.ManyToManyField(
                blank=True, null=True, to="directory_app.subject"
            ),
        ),
    ]
